apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: metrics
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/minio/minio/tree/master/helm/minio
      targetRevision: 5.3.0
      chart: minio
      helm:
        valueFiles:
          - $values/manifests/gem-minio-overrides.yaml
    - repoURL: https://github.com/pbmoses/ge-minio.git
      targetRevision: HEAD 
      ref: values
  project: default
